---
name: TODO to Issue

"on":
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
      - "**/CHANGELOG.md"
    tags-ignore:
      - "*"

permissions: write-all

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v4.13
        id: todo
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
